### ISSUE TITLE
Support read resources values

### ISSUE THREAD

**Issue by lazychanger** [lazychanger/helm-viv#4]
**dir**
```txt
├── Chart.yaml
├── templates
│   ├── NOTES.txt
│   ├── service.yaml
│   ├── ingress.yaml
├── vivs
│   ├── values.yaml
└── values.yaml
```

**templates/service.yaml**
```yaml
{{ if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
   ...
{{- end -}}
```

**.vivs/values.yaml**
```yaml
ingress
  enabled: {{ .Values.service.enabled }}
  service: {{ resource "v1" "Service" ".metadata.name" }}
```

**go func**
```go
func resource(apiVersion, kind, expr string) any {
   ...
}
```
